# Generated by Django 5.2.6 on 2025-09-24 14:17

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('description', wagtail.fields.RichTextField(verbose_name='Descrição da Vaga')),
                ('requirements', wagtail.fields.RichTextField(verbose_name='Requisitos')),
                ('benefits', wagtail.fields.RichTextField(blank=True, verbose_name='Benefícios')),
                ('job_type', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('freelancer', 'Freelancer'), ('temporario', 'Temporário')], max_length=20, verbose_name='Tipo de Contrato')),
                ('experience_level', models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista'), ('diretor', 'Diretor')], max_length=20, verbose_name='Nível de Experiência')),
                ('work_model', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='Modelo de Trabalho')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Mínimo')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Máximo')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente de Aprovação'), ('active', 'Ativa'), ('paused', 'Pausada'), ('closed', 'Fechada'), ('rejected', 'Rejeitada')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Candidatou-se'), ('under_review', 'Em Análise'), ('interview_scheduled', 'Entrevista Agendada'), ('interview_completed', 'Entrevista Realizada'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('hired', 'Contratado')], default='applied', max_length=20, verbose_name='Status')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Carta de Apresentação')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Candidatura')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrevista')),
                ('interview_notes', models.TextField(blank=True, verbose_name='Notas da Entrevista')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback da Empresa')),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Habilidade')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Habilidade da Vaga',
                'verbose_name_plural': 'Habilidades da Vaga',
                'unique_together': {('job', 'skill_name')},
            },
        ),
    ]
