# Generated by Django 5.2.6 on 2025-09-24 14:17

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descrição da Empresa')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('company_size', models.CharField(choices=[('micro', 'Microempresa (1-9 funcionários)'), ('pequena', 'Pequena empresa (10-49 funcionários)'), ('media', 'Média empresa (50-249 funcionários)'), ('grande', 'Grande empresa (250+ funcionários)')], max_length=20, verbose_name='Porte da Empresa')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Pessoa de Contato')),
                ('contact_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo do Contato')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn da Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil da Empresa',
                'verbose_name_plural': 'Perfis das Empresas',
            },
        ),
    ]
